VVV:
  files:
    - data/redumption/2016/WWZ_TuneCUETP8M1_13TeV-amcatnlo-pythia8.root
    - data/redumption/2016/WZZ_TuneCUETP8M1_13TeV-amcatnlo-pythia8.root
    - data/redumption/2016/ZZZ_TuneCUETP8M1_13TeV-amcatnlo-pythia8.root
  type: background
  color: 895

ZZ:
  files:
    - data/redumption/2016/ZZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8.root
    - data/redumption/2016/ZZTo4L_13TeV_powheg_pythia8_ext1.root
    - data/redumption/2016/ZZTo2L2Nu_13TeV_powheg_pythia8_ext1.root
    - data/redumption/2016/GluGluToContinToZZTo2e2mu_13TeV_MCFM701_pythia8.root
    - data/redumption/2016/GluGluToContinToZZTo2e2nu_13TeV_MCFM701_pythia8.root
    - data/redumption/2016/GluGluToContinToZZTo2e2tau_13TeV_MCFM701_pythia8.root
    - data/redumption/2016/GluGluToContinToZZTo2mu2nu_13TeV_MCFM701_pythia8.root
    - data/redumption/2016/GluGluToContinToZZTo2mu2tau_13TeV_MCFM701_pythia8.root
    - data/redumption/2016/GluGluToContinToZZTo4e_13TeV_MCFM701_pythia8.root
    - data/redumption/2016/GluGluToContinToZZTo4mu_13TeV_MCFM701_pythia8.root
    - data/redumption/2016/GluGluToContinToZZTo4tau_13TeV_MCFM701_pythia8.root
  type:
    background
  color: 798
WW:
  files:
    - data/redumption/2016/WWTo2L2Nu_13TeV-powheg.root
  color: 842
  type: background
WZ:
  files:
    - data/redumption/2016/WZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8.root
    - data/redumption/2016/WZTo3LNu_TuneCUETP8M1_13TeV-powheg-pythia8.root
  type:
    background
  kfactor: 1.00
  color: 856

DY:
  files:
    - data/redumption/2016/DYJetsToLL_Pt-100To250_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8.root
    - data/redumption/2016/DYJetsToLL_Pt-250To400_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8.root
    - data/redumption/2016/DYJetsToLL_Pt-400To650_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8.root
    - data/redumption/2016/DYJetsToLL_Pt-50To100_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8.root
    - data/redumption/2016/DYJetsToLL_Pt-650ToInf_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8.root
  type:
    background
  kfactor: 1.0
  color: 901

NonResonant:
  files:
    - data/redumption/2016/ST_tW_antitop_5f_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1.root
    - data/redumption/2016/ST_tW_top_5f_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1.root
    - data/redumption/2016/TTTo2L2Nu_TuneCP5_PSweights_13TeV-powheg-pythia8.root
    - data/redumption/2016/TTWJetsToLNu_TuneCUETP8M1_13TeV-amcatnloFXFX-madspin-pythia8.root
    - data/redumption/2016/TTWJetsToQQ_TuneCUETP8M1_13TeV-amcatnloFXFX-madspin-pythia8.root
    - data/redumption/2016/TTZToLLNuNu_M-10_TuneCUETP8M1_13TeV-amcatnlo-pythia8.root
    - data/redumption/2016/TTZToQQ_TuneCUETP8M1_13TeV-amcatnlo-pythia8.root
    - data/redumption/2016/DYJetsToTauTau_ForcedMuEleDecay_M-50_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8_ext1.root
  type:
    background
  color: 124
  kfactor: 2.0

data:
  files:
    - data/endgame/2016/DoubleEG_Run2016B_ver1-Nano1June2019_ver1-v1.root
    - data/endgame/2016/DoubleEG_Run2016B_ver2-Nano1June2019_ver2-v1.root
    - data/endgame/2016/DoubleEG_Run2016C-Nano1June2019-v1.root
    - data/endgame/2016/DoubleEG_Run2016D-Nano1June2019-v1.root
    - data/endgame/2016/DoubleEG_Run2016E-Nano1June2019-v1.root
    - data/endgame/2016/DoubleEG_Run2016F-Nano1June2019-v1.root
    - data/endgame/2016/DoubleEG_Run2016G-Nano1June2019-v1.root
    - data/endgame/2016/DoubleEG_Run2016H-Nano1June2019-v1.root
    - data/endgame/2016/DoubleMuon_Run2016B_ver1-Nano1June2019_ver1-v1.root
    - data/endgame/2016/DoubleMuon_Run2016B_ver2-Nano1June2019_ver2-v1.root
    - data/endgame/2016/DoubleMuon_Run2016C-Nano1June2019-v1.root
    - data/endgame/2016/DoubleMuon_Run2016D-Nano1June2019-v1.root
    - data/endgame/2016/DoubleMuon_Run2016E-Nano1June2019-v1.root
    - data/endgame/2016/DoubleMuon_Run2016F-Nano1June2019-v1.root
    - data/endgame/2016/DoubleMuon_Run2016G-Nano1June2019-v1.root
    - data/endgame/2016/DoubleMuon_Run2016H-Nano1June2019-v1.root
    - data/endgame/2016/MuonEG_Run2016B_ver1-Nano1June2019_ver1-v1.root
    - data/endgame/2016/MuonEG_Run2016B_ver2-Nano1June2019_ver2-v1.root
    - data/endgame/2016/MuonEG_Run2016C-Nano1June2019-v1.root
    - data/endgame/2016/MuonEG_Run2016D-Nano1June2019-v1.root
    - data/endgame/2016/MuonEG_Run2016E-Nano1June2019-v2.root
    - data/endgame/2016/MuonEG_Run2016E-Nano1June2019-v3.root
    - data/endgame/2016/MuonEG_Run2016F-Nano1June2019-v1.root
    - data/endgame/2016/MuonEG_Run2016G-Nano1June2019-v1.root
    - data/endgame/2016/MuonEG_Run2016H-Nano1June2019-v1.root
    - data/endgame/2016/SingleElectron_Run2016B_ver1-Nano1June2019_ver1-v1.root
    - data/endgame/2016/SingleElectron_Run2016B_ver2-Nano1June2019_ver2-v1.root
    - data/endgame/2016/SingleElectron_Run2016C-Nano1June2019-v1.root
    - data/endgame/2016/SingleElectron_Run2016D-Nano1June2019-v1.root
    - data/endgame/2016/SingleElectron_Run2016E-Nano1June2019-v1.root
    - data/endgame/2016/SingleElectron_Run2016F-Nano1June2019-v1.root
    - data/endgame/2016/SingleElectron_Run2016G-Nano1June2019-v1.root
    - data/endgame/2016/SingleElectron_Run2016H-Nano1June2019-v1.root
    - data/endgame/2016/SingleMuon_Run2016B_ver1-Nano1June2019_ver1-v1.root
    - data/endgame/2016/SingleMuon_Run2016B_ver2-Nano1June2019_ver2-v1.root
    - data/endgame/2016/SingleMuon_Run2016C-Nano1June2019-v1.root
    - data/endgame/2016/SingleMuon_Run2016D-Nano1June2019-v1.root
    - data/endgame/2016/SingleMuon_Run2016E-Nano1June2019-v1.root
    - data/endgame/2016/SingleMuon_Run2016F-Nano1June2019-v1.root
    - data/endgame/2016/SingleMuon_Run2016G-Nano1June2019-v1.root
    - data/endgame/2016/SingleMuon_Run2016H-Nano1June2019-v1.root
  type:
    data
  color: 1
ADD_MD_2_d_4:
  files:
    - data/redumption/2016/ADDMonoZ_ZtoLL_MD-2_d-4_TuneCUETP8M1_13TeV-pythia8.root
  type: signal
ADD_MD_1_d_4:
  files:
    - data/redumption/2016/ADDMonoZ_ZtoLL_MD-1_d-4_TuneCUETP8M1_13TeV-pythia8.root
  type: signal
ADD_MD_3_d_4:
  files:
    - data/redumption/2016/ADDMonoZ_ZToLL_MD-3_d-4_TuneCUETP8M1_13TeV-pythia8.root
  type: signal
