Other4l:
  files:
    - data/DY1JetsToLL_M-50_LHEZpT_50-150_TuneCP5_13TeV-amcnloFXFX-pythia8.root
    - data/DY1JetsToLL_M-50_LHEZpT_150-250_TuneCP5_13TeV-amcnloFXFX-pythia8.root
    - data/DY1JetsToLL_M-50_LHEZpT_250-400_TuneCP5_13TeV-amcnloFXFX-pythia8.root
    - data/DY1JetsToLL_M-50_LHEZpT_400-inf_TuneCP5_13TeV-amcnloFXFX-pythia8.root
    - data/DY2JetsToLL_M-50_LHEZpT_50-150_TuneCP5_13TeV-amcnloFXFX-pythia8.root
    - data/DY2JetsToLL_M-50_LHEZpT_150-250_TuneCP5_13TeV-amcnloFXFX-pythia8.root
    - data/DY2JetsToLL_M-50_LHEZpT_250-400_TuneCP5_13TeV-amcnloFXFX-pythia8.root
    - data/DY2JetsToLL_M-50_LHEZpT_400-inf_TuneCP5_13TeV-amcnloFXFX-pythia8.root
    - data/WZTo3LNu_0Jets_MLL-4to50_TuneCP5_13TeV-madgraphMLM-pythia8.root
    - data/WZTo3LNu_0Jets_MLL-50_TuneCP5_13TeV-madgraphMLM-pythia8.root
    - data/WZTo3LNu_1Jets_MLL-4to50_TuneCP5_13TeV-madgraphMLM-pythia8.root
    - data/WZTo3LNu_1Jets_MLL-50_TuneCP5_13TeV-madgraphMLM-pythia8.root
    - data/WZTo3LNu_2Jets_MLL-4to50_TuneCP5_13TeV-madgraphMLM-pythia8.root
    - data/WZTo3LNu_2Jets_MLL-50_TuneCP5_13TeV-madgraphMLM-pythia8.root
    - data/WZTo3LNu_3Jets_MLL-4to50_TuneCP5_13TeV-madgraphMLM-pythia8.root
    - data/WZTo3LNu_3Jets_MLL-50_TuneCP5_13TeV-madgraphMLM-pythia8.root
    - data/WZZ_TuneCP5_13TeV-amcatnlo-pythia8.root
    - data/ZZZ_TuneCP5_13TeV-amcatnlo-pythia8.root
    - data/ST_tW_antitop_5f_inclusiveDecays_TuneCP5_13TeV-powheg-pythia8.root
    - data/ST_tW_top_5f_inclusiveDecays_TuneCP5_13TeV-powheg-pythia8.root
    - data/TTTo2L2Nu_TuneCP5_13TeV-powheg-pythia8.root
    - data/TTTo2L2Nu_TuneCP5_PSweights_13TeV-powheg-pythia8.root
    - data/TTWJetsToLNu_TuneCP5_13TeV-amcatnloFXFX-madspin-pythia8.root
    - data/TTWJetsToQQ_TuneCP5_13TeV-amcatnloFXFX-madspin-pythia8.root
    - data/TTZToLLNuNu_M-10_TuneCP5_13TeV-amcatnlo-pythia8.root
    - data/TTZToQQ_TuneCP5_13TeV-amcatnlo-pythia8.root
    - data/ZZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8.root
    - data/WZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8.root
  type:
    background
Other3l:
  files:
    - data/DY1JetsToLL_M-50_LHEZpT_50-150_TuneCP5_13TeV-amcnloFXFX-pythia8.root
    - data/DY1JetsToLL_M-50_LHEZpT_150-250_TuneCP5_13TeV-amcnloFXFX-pythia8.root
    - data/DY1JetsToLL_M-50_LHEZpT_250-400_TuneCP5_13TeV-amcnloFXFX-pythia8.root
    - data/DY1JetsToLL_M-50_LHEZpT_400-inf_TuneCP5_13TeV-amcnloFXFX-pythia8.root
    - data/DY2JetsToLL_M-50_LHEZpT_50-150_TuneCP5_13TeV-amcnloFXFX-pythia8.root
    - data/DY2JetsToLL_M-50_LHEZpT_150-250_TuneCP5_13TeV-amcnloFXFX-pythia8.root
    - data/DY2JetsToLL_M-50_LHEZpT_250-400_TuneCP5_13TeV-amcnloFXFX-pythia8.root
    - data/DY2JetsToLL_M-50_LHEZpT_400-inf_TuneCP5_13TeV-amcnloFXFX-pythia8.root
    - data/WZZ_TuneCP5_13TeV-amcatnlo-pythia8.root
    - data/ZZZ_TuneCP5_13TeV-amcatnlo-pythia8.root
    - data/ST_tW_antitop_5f_inclusiveDecays_TuneCP5_13TeV-powheg-pythia8.root
    - data/ST_tW_top_5f_inclusiveDecays_TuneCP5_13TeV-powheg-pythia8.root
    - data/TTTo2L2Nu_TuneCP5_13TeV-powheg-pythia8.root
    - data/TTTo2L2Nu_TuneCP5_PSweights_13TeV-powheg-pythia8.root
    - data/TTWJetsToLNu_TuneCP5_13TeV-amcatnloFXFX-madspin-pythia8.root
    - data/TTWJetsToQQ_TuneCP5_13TeV-amcatnloFXFX-madspin-pythia8.root
    - data/TTZToLLNuNu_M-10_TuneCP5_13TeV-amcatnlo-pythia8.root
    - data/TTZToQQ_TuneCP5_13TeV-amcatnlo-pythia8.root
    - data/ZZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8.root
    - data/WZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8.root
  type:
    background
Nonresonant:
  files:
    - data/ST_tW_antitop_5f_inclusiveDecays_TuneCP5_13TeV-powheg-pythia8.root
    - data/ST_tW_top_5f_inclusiveDecays_TuneCP5_13TeV-powheg-pythia8.root
    - data/TTZToLLNuNu_M-10_TuneCP5_13TeV-amcatnlo-pythia8.root
    - data/WWTo2L2Nu_NNPDF31_TuneCP5_PSweights_13TeV-powheg-pythia8.root
    - data/WWTo2L2Nu_NNPDF31_TuneCP5_13TeV-powheg-pythia8.root
    - data/DYJetsToTauTau_ForcedMuEleDecay_M-50_TuneCP5_PSweights_13TeV-amcatnloFXFX-pythia8.root
  type:
    background


qqZZ4l:
  files:
    - data/ZZTo4L_13TeV_powheg_pythia8.root
  type:
    background

ggZZ4l:
  files:
    - data/GluGluToContinToZZTo2e2mu_13TeV_MCFM701_pythia8.root
    - data/GluGluToContinToZZTo2e2tau_13TeV_MCFM701_pythia8.root
    - data/GluGluToContinToZZTo2mu2tau_13TeV_MCFM701_pythia8.root
    - data/GluGluToContinToZZTo4e_13TeV_MCFM701_pythia8.root
    - data/GluGluToContinToZZTo4mu_13TeV_MCFM701_pythia8.root
    - data/GluGluToContinToZZTo4tau_13TeV_MCFM701_pythia8.root
  type:
    background

qqZZ2l2nu:
  files:
    - data/ZZTo2L2Nu_13TeV_powheg_pythia8.root
  type:
    background

ggZZ2l2nu:
  files:
    - data/GluGluToContinToZZTo2mu2nu_13TeV_MCFM701_pythia8.root
    - data/GluGluToContinToZZTo2e2nu_13TeV_MCFM701_pythia8.root
  type:
    background

DrellYanBinned:
  files:
    - data/DY1JetsToLL_M-50_LHEZpT_50-150_TuneCP5_13TeV-amcnloFXFX-pythia8.root
    - data/DY1JetsToLL_M-50_LHEZpT_150-250_TuneCP5_13TeV-amcnloFXFX-pythia8.root
    - data/DY1JetsToLL_M-50_LHEZpT_250-400_TuneCP5_13TeV-amcnloFXFX-pythia8.root
    - data/DY1JetsToLL_M-50_LHEZpT_400-inf_TuneCP5_13TeV-amcnloFXFX-pythia8.root
    - data/DY2JetsToLL_M-50_LHEZpT_50-150_TuneCP5_13TeV-amcnloFXFX-pythia8.root
    - data/DY2JetsToLL_M-50_LHEZpT_150-250_TuneCP5_13TeV-amcnloFXFX-pythia8.root
    - data/DY2JetsToLL_M-50_LHEZpT_250-400_TuneCP5_13TeV-amcnloFXFX-pythia8.root
    - data/DY2JetsToLL_M-50_LHEZpT_400-inf_TuneCP5_13TeV-amcnloFXFX-pythia8.root
  type:
    background

WZ3lnu:
  files:
    - data/WZTo3LNu_0Jets_MLL-4to50_TuneCP5_13TeV-madgraphMLM-pythia8.root
    - data/WZTo3LNu_0Jets_MLL-50_TuneCP5_13TeV-madgraphMLM-pythia8.root
    - data/WZTo3LNu_1Jets_MLL-4to50_TuneCP5_13TeV-madgraphMLM-pythia8.root
    - data/WZTo3LNu_1Jets_MLL-50_TuneCP5_13TeV-madgraphMLM-pythia8.root
    - data/WZTo3LNu_2Jets_MLL-4to50_TuneCP5_13TeV-madgraphMLM-pythia8.root
    - data/WZTo3LNu_2Jets_MLL-50_TuneCP5_13TeV-madgraphMLM-pythia8.root
    - data/WZTo3LNu_3Jets_MLL-4to50_TuneCP5_13TeV-madgraphMLM-pythia8.root
    - data/WZTo3LNu_3Jets_MLL-50_TuneCP5_13TeV-madgraphMLM-pythia8.root
  type:
    background

Other:
  files:
    - data/ST_tW_antitop_5f_inclusiveDecays_TuneCP5_13TeV-powheg-pythia8.root
    - data/ST_tW_top_5f_inclusiveDecays_TuneCP5_13TeV-powheg-pythia8.root
    - data/TTTo2L2Nu_TuneCP5_13TeV-powheg-pythia8.root
    - data/TTTo2L2Nu_TuneCP5_PSweights_13TeV-powheg-pythia8.root
    - data/TTWJetsToLNu_TuneCP5_13TeV-amcatnloFXFX-madspin-pythia8.root
    - data/TTWJetsToQQ_TuneCP5_13TeV-amcatnloFXFX-madspin-pythia8.root
    - data/TTZToLLNuNu_M-10_TuneCP5_13TeV-amcatnlo-pythia8.root
    - data/TTZToQQ_TuneCP5_13TeV-amcatnlo-pythia8.root
    - data/ZZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8.root
    - data/WZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8.root
    - data/WZZ_TuneCP5_13TeV-amcatnlo-pythia8.root
    - data/ZZZ_TuneCP5_13TeV-amcatnlo-pythia8.root
    - data/ZZTo4L_13TeV_powheg_pythia8.root
    - data/GluGluToContinToZZTo2e2mu_13TeV_MCFM701_pythia8.root
    - data/GluGluToContinToZZTo2e2tau_13TeV_MCFM701_pythia8.root
    - data/GluGluToContinToZZTo2mu2tau_13TeV_MCFM701_pythia8.root
    - data/GluGluToContinToZZTo4e_13TeV_MCFM701_pythia8.root
    - data/GluGluToContinToZZTo4mu_13TeV_MCFM701_pythia8.root
    - data/GluGluToContinToZZTo4tau_13TeV_MCFM701_pythia8.root
  type:
    background
Data:
  files:
    - data/DoubleEG_Run2017B-31Mar2018-v1.root
    - data/DoubleEG_Run2017C-31Mar2018-v1.root
    - data/DoubleEG_Run2017D-31Mar2018-v1.root
    - data/DoubleEG_Run2017E-31Mar2018-v1.root
    - data/DoubleEG_Run2017F-31Mar2018-v1.root
    - data/DoubleMuon_Run2017B-31Mar2018-v1.root
    - data/DoubleMuon_Run2017C-31Mar2018-v1.root
    - data/DoubleMuon_Run2017D-31Mar2018-v1.root
    - data/DoubleMuon_Run2017E-31Mar2018-v1.root
    - data/DoubleMuon_Run2017F-31Mar2018-v1.root
    - data/MuonEG_Run2017B-31Mar2018-v1.root
    - data/MuonEG_Run2017C-31Mar2018-v1.root
    - data/MuonEG_Run2017D-31Mar2018-v1.root
    - data/MuonEG_Run2017E-31Mar2018-v1.root
    - data/MuonEG_Run2017F-31Mar2018-v1.root
    - data/SingleElectron_Run2017B-31Mar2018-v1.root
    - data/SingleElectron_Run2017C-31Mar2018-v1.root
    - data/SingleElectron_Run2017D-31Mar2018-v1.root
    - data/SingleElectron_Run2017E-31Mar2018-v1.root
    - data/SingleElectron_Run2017F-31Mar2018-v1.root
    - data/SingleMuon_Run2017B-31Mar2018-v1.root
    - data/SingleMuon_Run2017C-31Mar2018-v1.root
    - data/SingleMuon_Run2017D-31Mar2018-v1.root
    - data/SingleMuon_Run2017E-31Mar2018-v1.root
    - data/SingleMuon_Run2017F-31Mar2018-v1.root
  type:
    data
  color: 1

DMY1000Xd10:
  files:
    - data/DMSimp_MonoZLL_NLO_Vector_TuneCP3_GQ0p25_GDM1p0_MY1-1000_MXd-10.root
  type:
    signal

DMY1000Xd10:
  files:
    - data/DMSimp_MonoZLL_NLO_Vector_TuneCP3_GQ0p25_GDM1p0_MY1-1000_MXd-10.root
  type:
    signal

DMY1000Xd100:
  files:
    - data/DMSimp_MonoZLL_NLO_Vector_TuneCP3_GQ0p25_GDM1p0_MY1-1000_MXd-100.root
  type:
    signal

DMY1000Xd200:
  files:
    - data/DMSimp_MonoZLL_NLO_Vector_TuneCP3_GQ0p25_GDM1p0_MY1-1000_MXd-200.root
  type:
    signal

DMY1000Xd300:
  files:
    - data/DMSimp_MonoZLL_NLO_Vector_TuneCP3_GQ0p25_GDM1p0_MY1-1000_MXd-300.root
  type:
    signal
DMY1000Xd400:
  files:
    - data/DMSimp_MonoZLL_NLO_Vector_TuneCP3_GQ0p25_GDM1p0_MY1-1000_MXd-400.root
  type:
    signal

DMY1000Xd510:
  files:
    - data/DMSimp_MonoZLL_NLO_Vector_TuneCP3_GQ0p25_GDM1p0_MY1-1000_MXd-510.root
  type:
    signal

DMY1250Xd1:
  files:
    - data/DMSimp_MonoZLL_NLO_Vector_TuneCP3_GQ0p25_GDM1p0_MY1-1250_MXd-1.root
  type:
    signal
DMY1500Xd1:
  files:
    - data/DMSimp_MonoZLL_NLO_Vector_TuneCP3_GQ0p25_GDM1p0_MY1-1500_MXd-1.root
  type:
    signal
DMY1750Xd1:
  files:
    - data/DMSimp_MonoZLL_NLO_Vector_TuneCP3_GQ0p25_GDM1p0_MY1-1750_MXd-1.root
  type:
    signal
DMY2000Xd1:
  files:
    - data/DMSimp_MonoZLL_NLO_Vector_TuneCP3_GQ0p25_GDM1p0_MY1-2000_MXd-1.root
  type:
    signal
DMY250Xd1:
  files:
    - data/DMSimp_MonoZLL_NLO_Vector_TuneCP3_GQ0p25_GDM1p0_MY1-250_MXd-1.root
  type:
    signal
DMY500Xd1:
  files:
    - data/DMSimp_MonoZLL_NLO_Vector_TuneCP3_GQ0p25_GDM1p0_MY1-500_MXd-1.root
  type:
    signal
